target 'iosApp' do
  use_frameworks!
  platform :ios, '16.0'
  pod 'shared', :path => '../shared'
  pod 'sharedSwift', :path => '../shared'
  pod 'mokoMvvmFlowSwiftUI', :podspec => 'https://raw.githubusercontent.com/icerockdev/moko-mvvm/release/0.16.1/mokoMvvmFlowSwiftUI.podspec'
  #pod 'FirebaseFirestore'
  #pod 'FirebaseUI/Auth'
  #pod 'FirebaseUI/Google'
  #pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc
end

# インストール後に実行される処理
post_install do |installer|
    xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`
    # 既存のスクリプトなどで以下が記載されている場合、↑の変数だけ追加すればOK
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            # Xcode 15以上で動作します(if内を追記)
            if config.base_configuration_reference && Integer(xcode_base_version) >= 15
                xcconfig_path = config.base_configuration_reference.real_path
                xcconfig = File.read(xcconfig_path)
                xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
                File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
            end
        end
    end
end